{{- with .Values.rbacAuthorizationClusterRoleAppscodeAppcatalogView }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- .metadata | toYaml | nindent 2 }}
rules:
  {{- .rules | toYaml | nindent 2 }}
{{- end }}
